### ISSUE TITLE
Peer Review #2

### ISSUE THREAD

**Issue by jamiejiminlee** [koyunkyung/infant_health#2]
### Opening Statement Summary
This paper examines the impact of maternal drug use during labor and delivery on neonatal health, using the 5-minute Apgar score. It combines Random Forest model for prediction and Bayesian Linear Model for inference. The paper reveals the drugs with the biggest impact on Apgar scores and provides insight into better labor-associated treatments.

### Strong Positive Points

- Good choice of data model using both predictive and inferential modeling
- Paper is well organized with good visualizations
- Strong model details and measurement sections

### Critical Improvements Needed

- Improve title; Title needs to tell readers what was found in the paper
- Address any potential limitations of the analysis - bias in data, model validity, etc

### Suggestions for Improvement

- More detailed captions for visualizations
- Better formatting with visualizations - they are not in order with the paper text
- Talk more about priors for the model

### Evaluation

**R/Python cited** (1/1)
**Data cited** (1/1)
**Class paper** (1/1)
**LLM documentation** (1/1 pts)
**Title** (1/2)
Comment: tell readers what the paper finds
**Author, date, and repo** (2/2)
**Abstract** (4/4)
**Introduction** (3/4)
**Estimand** (1/1)
**Data** (7/10)
Comment: Requires better formatting - visuals not in right place
**Measurement** (8/10)
**Model** (7/10)
Comment: could add more for model justification
**Results** (7/10)
Comment: could add more explanation 
**Discussion** (8/10)
**Prose** (6/6)
**Cross-references** (1/1)
**Captions** (1/2)
**Graphs/tables/etc** (3.5/4)
Comment: Format properly
**Surveys, sampling, and observational data appendix** (5/10)
Comment: Can add more content
**Referencing** (4/4)
**Commits** (2/2)
**Sketches** (2/2)
**Simulation** (4/4)
**Tests** (4/4)
**Parquet** (1/1)
**Reproducible** **workflow** (4/4)
**Enhancements** (2/4)
**Miscellaneous** (2/3)

### Estimated Overall Mark
93.5/112

### Any Other Comments
Great start to your paper, just needs a bit of polishing!

**Comment by koyunkyung** [comment]
Thank you so much for your time reviewing my repo. Following your comments, I tried to specify more on the justification part of the prediction models (especially the priors and assumptions), and supplement the appendix for surveys, sampling, and observational data.
