### ISSUE TITLE
peer review 3

### ISSUE THREAD

**Issue by michj3** [koyunkyung/infant_health#4]
Summary
I am peer reviewing Yunkyung's paper on drug usage and infant health. 

Strong positive points:
- The introduction is clear and straight to the point, very nicely structured.
- You give a lot of good examples when explaining, especially in the measurement and introduction, which makes it easier to follow for readers, nice!
- The graphs are nicely made and visually appealing, with labels on count. 

Critical improvements needed:
- Review grammar and sentence structure. Some sentences are not complete (ex: first sentence of abstract)
- Although appreciated, the "notes" in the figure captions are informal. They could be included either in the actual paper or in an appendix. 
- review proper reference format

Suggestions for improvement:
- Some of the citations need to be fixed. I think n.d stands for no date, but that shouldn't appear in the in text citation. 
- You use the phrase "we did this...", "we did that...". I think making your paper a bit more professional would help increase the validity of your paper, so you should consider removing phrases like 'we' and make it more formal. 
- Some of the paragraphs in the data section only consist of 1 or 2 sentences, which makes the paragraph seem a little unnecessary. maybe considering combining predcitor variables and response into their own paragraphs so it's a bit more cohesive. 
- Figures 23-25: you could consider putting them into 1 plot together, so each doesn't take up an entire page, just for visualization appeal. 
- You should consider looking at the "enhancements" section of the rubric and include something from there

Evaluation:
- R/Python cited (1/1 pts): yes
- Data cited (1/1 pts): yes
- Class paper (1/1 pts): no indication of class paper
- LLM documentation (1/1 pts): yes
- Title (2/2 pts): good 
- Author, date, and repo (2/2 pts): yes
- Abstract (3/4 pts): review grammar and sentence structure
- Introduction (3/4 pts): clear, but review prose and grammar
- Estimand (1/1 pts): clearly stated
- Data (8/10 pts): good, fix structure
- Measurement (4/4 pts): clearly stated
- Model (9/10 pts): nice
- Results (10/10 pts): goes in depth
- Discussion (10/10 pts): very in depth 
- Prose (4/6 pts): fix grammar and review prose words not to use
- Cross-references (1/1 pts): good
- Captions (1/2 pts): good, but look at above comment about "note"
- Graphs/tables/etc (4/4 pts): very nicely made
- Surveys, sampling, and observational data appendix (10/10 pts): in depht, good
- Referencing (2/4 pts): review proper referencing format and "n.d" issue
- Commits (2/2 pts): good
- Sketches (2/2 pts): good
- Simulation (4/4 pts): good
- Tests (4/4 pts): good
- Parquet (1/1 pts): present
- Reproducible workflow (4/4 pts): good
- Enhancements (0/4 pts): not there 
- Miscellaneous (1/3 pts): graphs are really nice

Estimated overall mark:
96 out of 112.

**Comment by koyunkyung** [comment]
Thank you so much for your time reviewing my repo. Following your comments, I tried to revise the entire prose of the paper in a more formal/ academic manner, fix reference errors, and improve the formatting of some figures and captions.
